### ISSUE TITLE
[Bug Report]:  [ModernPluginLoadingStrategy] 

### ISSUE THREAD

**Issue by vc606** [Crazy-Crew/CrazyEnchantments#723]
### Server Version

1.20.1

### Server Platform

Paper

### Describe the bug

paper 1.20.1-108
crazy enchantments 2.0.1
java:amazon corretto 17

The version 2.0.1 of the plugin is unable to load properly.

https://pastebin.com/fLb4EydV
`[05:39:47 ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'CrazyEnchantments-2.0.1 (1).jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Cannot find main class `com.badbones69.crazyenchantments.paper.CrazyEnchantments'
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[paper-1.20.1.jar:git-Paper-108]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[paper-1.20.1.jar:git-Paper-108]
        at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[paper-1.20.1.jar:git-Paper-108]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.20.1.jar:git-Paper-108]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.1.jar:git-Paper-108]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:508) ~[paper-1.20.1.jar:git-Paper-108]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.20.1.jar:git-Paper-108]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-108]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-108]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.badbones69.crazyenchantments.paper.CrazyEnchantments
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:467) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        ... 10 more`

### Steps to reproduce

Start the server to load the plugin

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by CrazyCrew.

**Comment by ryderbelserion** [comment]
1) doesn't support 1.19.4
2) Re-download the version

**Comment by vc606** [comment]
> 1. doesn't support 1.19.4
> 2. Re-download the version

I am using paper 1.20.1. After re-downloading, it is now working normally. Sorry, the file I originally downloaded may have been damaged?! But now it can be read normally. Thank you very much.
