### ISSUE TITLE
Boom I enchant possibly causing infinite error cycling

### ISSUE THREAD

**Issue by oEGGLORDo** [Crazy-Crew/CrazyEnchantments#811]
### Plugin Version

2.2.8

### Server Version

1.20.2

### Server Platform

Paper

### Describe the bug

It appears that an error keeps occurring where the main error is as follows:
Could not pass event EntityDamageByBlockEvent to CrazyEnchantments v2.2.8

The rest of the repeating error message is as follows

`23.04 12:40:13 [Server] ERROR Could not pass event EntityDamageByBlockEvent to CrazyEnchantments v2.2.8
23.04 12:40:13 [Server] INFO java.lang.NoSuchMethodError: 'org.bukkit.damage.DamageSource org.bukkit.event.entity.EntityDamageEvent.getDamageSource()'
23.04 12:40:13 [Server] INFO at com.badbones69.crazyenchantments.paper.listeners.FireworkDamageListener.onFireworkDamage(FireworkDamageListener.java:25) ~[CrazyEnchantments-2.2.8.jar:?]
23.04 12:40:13 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor137.execute(Unknown Source) ~[?:?]
23.04 12:40:13 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
23.04 12:40:13 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
23.04 12:40:13 [Server] INFO at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
23.04 12:40:13 [Server] INFO at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callEvent(CraftEventFactory.java:266) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1089) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1016) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1251) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2218) ~[?:?]
23.04 12:40:13 [Server] INFO at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1463) ~[?:?]
23.04 12:40:13 [Server] INFO at net.minecraft.world.entity.ambient.Bat.hurt(Bat.java:207) ~[?:?]
23.04 12:40:13 [Server] INFO at net.minecraft.world.entity.Entity.lavaHurt(Entity.java:905) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at net.minecraft.world.entity.Entity.baseTick(Entity.java:828) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at net.minecraft.world.entity.LivingEntity.baseTick(LivingEntity.java:407) ~[?:?]
23.04 12:40:13 [Server] INFO at net.minecraft.world.entity.Mob.baseTick(Mob.java:363) ~[?:?]
23.04 12:40:13 [Server] INFO at net.minecraft.world.entity.Entity.tick(Entity.java:768) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3000) ~[?:?]
23.04 12:40:13 [Server] INFO at net.minecraft.world.entity.Mob.tick(Mob.java:436) ~[?:?]
23.04 12:40:13 [Server] INFO at net.minecraft.world.entity.ambient.Bat.tick(Bat.java:121) ~[?:?]
23.04 12:40:13 [Server] INFO at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1386) ~[?:?]
23.04 12:40:13 [Server] INFO at net.minecraft.world.level.Level.guardEntityTick(Level.java:1309) ~[?:?]
23.04 12:40:13 [Server] INFO at net.minecraft.server.level.ServerLevel.lambda$tick$8(ServerLevel.java:900) ~[?:?]
23.04 12:40:13 [Server] INFO at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:880) ~[?:?]
23.04 12:40:13 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1548) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1379) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
23.04 12:40:13 [Server] ERROR Could not pass event EntityDamageByBlockEvent to CrazyEnchantments v2.2.8
23.04 12:40:13 [Server] INFO java.lang.NoSuchMethodError: 'org.bukkit.damage.DamageSource org.bukkit.event.entity.EntityDamageEvent.getDamageSource()'
23.04 12:40:13 [Server] INFO at com.badbones69.crazyenchantments.paper.listeners.FireworkDamageListener.onFireworkDamage(FireworkDamageListener.java:25) ~[CrazyEnchantments-2.2.8.jar:?]
23.04 12:40:13 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor137.execute(Unknown Source) ~[?:?]
23.04 12:40:13 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
23.04 12:40:13 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
23.04 12:40:13 [Server] INFO at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
23.04 12:40:13 [Server] INFO at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callEvent(CraftEventFactory.java:266) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1089) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1016) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1251) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2218) ~[?:?]
23.04 12:40:13 [Server] INFO at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1463) ~[?:?]
23.04 12:40:13 [Server] INFO at net.minecraft.world.entity.ambient.Bat.hurt(Bat.java:207) ~[?:?]
23.04 12:40:13 [Server] INFO at net.minecraft.world.entity.Entity.lavaHurt(Entity.java:905) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at net.minecraft.world.entity.Entity.baseTick(Entity.java:828) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at net.minecraft.world.entity.LivingEntity.baseTick(LivingEntity.java:407) ~[?:?]
23.04 12:40:13 [Server] INFO at net.minecraft.world.entity.Mob.baseTick(Mob.java:363) ~[?:?]
23.04 12:40:13 [Server] INFO at net.minecraft.world.entity.Entity.tick(Entity.java:768) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3000) ~[?:?]
23.04 12:40:13 [Server] INFO at net.minecraft.world.entity.Mob.tick(Mob.java:436) ~[?:?]
23.04 12:40:13 [Server] INFO at net.minecraft.world.entity.ambient.Bat.tick(Bat.java:121) ~[?:?]
23.04 12:40:13 [Server] INFO at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1386) ~[?:?]
23.04 12:40:13 [Server] INFO at net.minecraft.world.level.Level.guardEntityTick(Level.java:1309) ~[?:?]
23.04 12:40:13 [Server] INFO at net.minecraft.server.level.ServerLevel.lambda$tick$8(ServerLevel.java:900) ~[?:?]
23.04 12:40:13 [Server] INFO at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:880) ~[?:?]
23.04 12:40:13 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1548) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1379) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
23.04 12:40:13 [Server] ERROR Could not pass event EntityDamageByBlockEvent to CrazyEnchantments v2.2.8
23.04 12:40:13 [Server] INFO java.lang.NoSuchMethodError: 'org.bukkit.damage.DamageSource org.bukkit.event.entity.EntityDamageEvent.getDamageSource()'
23.04 12:40:13 [Server] INFO at com.badbones69.crazyenchantments.paper.listeners.FireworkDamageListener.onFireworkDamage(FireworkDamageListener.java:25) ~[CrazyEnchantments-2.2.8.jar:?]
23.04 12:40:13 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor137.execute(Unknown Source) ~[?:?]
23.04 12:40:13 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
23.04 12:40:13 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
23.04 12:40:13 [Server] INFO at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
23.04 12:40:13 [Server] INFO at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callEvent(CraftEventFactory.java:266) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1089) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1016) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1251) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2218) ~[?:?]
23.04 12:40:13 [Server] INFO at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1463) ~[?:?]
23.04 12:40:13 [Server] INFO at net.minecraft.world.entity.ambient.Bat.hurt(Bat.java:207) ~[?:?]
23.04 12:40:13 [Server] INFO at net.minecraft.world.entity.Entity.lavaHurt(Entity.java:905) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at net.minecraft.world.entity.Entity.baseTick(Entity.java:828) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at net.minecraft.world.entity.LivingEntity.baseTick(LivingEntity.java:407) ~[?:?]
23.04 12:40:13 [Server] INFO at net.minecraft.world.entity.Mob.baseTick(Mob.java:363) ~[?:?]
23.04 12:40:13 [Server] INFO at net.minecraft.world.entity.Entity.tick(Entity.java:768) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3000) ~[?:?]
23.04 12:40:13 [Server] INFO at net.minecraft.world.entity.Mob.tick(Mob.java:436) ~[?:?]
23.04 12:40:13 [Server] INFO at net.minecraft.world.entity.ambient.Bat.tick(Bat.java:121) ~[?:?]
23.04 12:40:13 [Server] INFO at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1386) ~[?:?]
23.04 12:40:13 [Server] INFO at net.minecraft.world.level.Level.guardEntityTick(Level.java:1309) ~[?:?]
23.04 12:40:13 [Server] INFO at net.minecraft.server.level.ServerLevel.lambda$tick$8(ServerLevel.java:900) ~[?:?]
23.04 12:40:13 [Server] INFO at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:880) ~[?:?]
23.04 12:40:13 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1548) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1379) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
23.04 12:40:13 [Server] ERROR Could not pass event EntityDamageByBlockEvent to CrazyEnchantments v2.2.8
23.04 12:40:13 [Server] INFO java.lang.NoSuchMethodError: 'org.bukkit.damage.DamageSource org.bukkit.event.entity.EntityDamageEvent.getDamageSource()'
23.04 12:40:13 [Server] INFO at com.badbones69.crazyenchantments.paper.listeners.FireworkDamageListener.onFireworkDamage(FireworkDamageListener.java:25) ~[CrazyEnchantments-2.2.8.jar:?]
23.04 12:40:13 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor137.execute(Unknown Source) ~[?:?]
23.04 12:40:13 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
23.04 12:40:13 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
23.04 12:40:13 [Server] INFO at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
23.04 12:40:13 [Server] INFO at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callEvent(CraftEventFactory.java:266) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1089) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1016) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1251) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2218) ~[?:?]
23.04 12:40:13 [Server] INFO at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1463) ~[?:?]
23.04 12:40:13 [Server] INFO at net.minecraft.world.entity.ambient.Bat.hurt(Bat.java:207) ~[?:?]
23.04 12:40:13 [Server] INFO at net.minecraft.world.entity.Entity.lavaHurt(Entity.java:905) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at net.minecraft.world.entity.Entity.baseTick(Entity.java:828) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at net.minecraft.world.entity.LivingEntity.baseTick(LivingEntity.java:407) ~[?:?]
23.04 12:40:13 [Server] INFO at net.minecraft.world.entity.Mob.baseTick(Mob.java:363) ~[?:?]
23.04 12:40:13 [Server] INFO at net.minecraft.world.entity.Entity.tick(Entity.java:768) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3000) ~[?:?]
23.04 12:40:13 [Server] INFO at net.minecraft.world.entity.Mob.tick(Mob.java:436) ~[?:?]
23.04 12:40:13 [Server] INFO at net.minecraft.world.entity.ambient.Bat.tick(Bat.java:121) ~[?:?]
23.04 12:40:13 [Server] INFO at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1386) ~[?:?]
23.04 12:40:13 [Server] INFO at net.minecraft.world.level.Level.guardEntityTick(Level.java:1309) ~[?:?]
23.04 12:40:13 [Server] INFO at net.minecraft.server.level.ServerLevel.lambda$tick$8(ServerLevel.java:900) ~[?:?]
23.04 12:40:13 [Server] INFO at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:880) ~[?:?]
23.04 12:40:13 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1548) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1379) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-234]
23.04 12:40:13 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]`

Based on my limited knowledge, it appears the error

### Crate Type

None

### Steps to reproduce

1. Occurs on server start up and repeats.

### Additional context

I've removed the bow that I created with Boom I yet the error still persists. I believe it is due to the bow since the calls for fireworks and damage and identifies this plugin as the culprit.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by CrazyCrew.

**Comment by ryderbelserion** [comment]
Outdated version of Minecraft, This error gets fixed the moment you use 1.20.4
