### ISSUE TITLE
FOLIA  ERROR

### ISSUE THREAD

**Issue by 404forever1** [Crazy-Crew/CrazyEnchantments#827]
### Plugin Version

CrazyEnchantments 2.3

### Server Version

1.20.4

### Server Platform

Folia

### Describe the bug

CANT WORK

### Steps to reproduce

[14:36:37 ERROR]: Error occurred while enabling CrazyEnchantments v2.3 (Is it up to date?)
java.lang.NoSuchMethodError: 'void org.bukkit.inventory.meta.ItemMeta.setEnchantmentGlintOverride(java.lang.Boolean)'
        at com.badbones69.crazyenchantments.paper.api.builders.ItemBuilder.addGlow(ItemBuilder.java:1321) ~[CrazyEnchantments-2.3.jar:?]
        at com.badbones69.crazyenchantments.paper.api.builders.ItemBuilder.build(ItemBuilder.java:533) ~[CrazyEnchantments-2.3.jar:?]
        at com.badbones69.crazyenchantments.paper.api.CrazyManager.load(CrazyManager.java:258) ~[CrazyEnchantments-2.3.jar:?]
        at com.badbones69.crazyenchantments.paper.CrazyEnchantments.onEnable(CrazyEnchantments.java:88) ~[CrazyEnchantments-2.3.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[luminol-1.20.4.jar:git-Luminol-"59a428e"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[luminol-1.20.4.jar:git-Luminol-"59a428e"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:646) ~[luminol-1.20.4.jar:git-Luminol-"59a428e"]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:557) ~[luminol-1.20.4.jar:git-Luminol-"59a428e"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:713) ~[luminol-1.20.4.jar:git-Luminol-"59a428e"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:458) ~[luminol-1.20.4.jar:git-Luminol-"59a428e"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:312) ~[luminol-1.20.4.jar:git-Luminol-"59a428e"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1217) ~[luminol-1.20.4.jar:git-Luminol-"59a428e"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:346) ~[luminol-1.20.4.jar:git-Luminol-"59a428e"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by CrazyCrew.

**Comment by ryderbelserion** [comment]
it says in supported versions 1.20.6 support only

**Comment by 404forever1** [comment]
> it says in supported versions 1.20.6 support only for 2.3

ok，Is there an opportunity to support 1.20.4?

**Comment by ryderbelserion** [comment]
No, We arent maintaining 2 versions of CrazyEnchantments.
