### ISSUE TITLE
Could not pass event EntityDamageByEntityEvent to CrazyEnchantments v2.2.8

### ISSUE THREAD

**Issue by SpeakingOrc785** [Crazy-Crew/CrazyEnchantments#831]
### Plugin Version

2.2.8

### Server Version

1.20.4

### Server Platform

Spigot

### Describe the bug

- [Wed 20:18:07 ERROR Minecraft] Could not pass event EntityDamageByEntityEvent to CrazyEnchantments v2.2.8
java.lang.IllegalArgumentException: x not finite
    at org.bukkit.util.NumberConversions.checkFinite(NumberConversions.java:118)
    at org.bukkit.util.Vector.checkFinite(Vector.java:872)
    at org.bukkit.craftbukkit.v1_20_R3.entity.CraftEntity.setVelocity(CraftEntity.java:140)
    at CrazyEnchantments-2.2.8 (1).jar//com.badbones69.crazyenchantments.paper.enchantments.BowEnchantments.onArrowDamage(BowEnchantments.java:186)
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor398.execute(Unknown Source)
    at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
    at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
    at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:267)
    at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1203)
    at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1188)
    at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1120)
    at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1081)
    at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1237)
    at net.minecraft.world.entity.LivingEntity.actuallyHurt(LivingEntity.java:2243)
    at net.minecraft.world.entity.player.Player.actuallyHurt(Player.java:1063)
    at net.minecraft.world.entit

### Steps to reproduce

Unknown

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by CrazyCrew.

**Comment by ryderbelserion** [comment]
We do not support Spigot, You must use https://papermc.io/
