### ISSUE TITLE
 [ModernPluginLoadingStrategy] Could not load plugin 'CrazyEnchantments-2.5 (2).jar' in folder 'plugins'

### ISSUE THREAD

**Issue by servicomcr** [Crazy-Crew/CrazyEnchantments#859]
### Plugin Version

CrazyEnchantments-2.5

### Server Version

1.21.1

### Server Platform

Paper

### Describe the bug

[17:59:00 INFO]: [SpigotLibraryLoader] [nightcore] Loaded library /home/container/libraries/it/unimi/dsi/fastutil-core/8.5.13/fastutil-core-8.5.13.jar
[17:59:00 ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'CrazyEnchantments-2.5 (2).jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.21.1
        at org.bukkit.craftbukkit.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:369) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:121) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:560) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:326) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

### Steps to reproduce

....

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by CrazyCrew.

**Comment by ryderbelserion** [comment]
1.21 is not supported, You must use 1.21.1
